class CurrencyDto {
  final String code;   // es. "EUR"
  final String symbol; // es. "€"
  final String name;   // es. "Euro"

  const CurrencyDto({required this.code, required this.symbol, required this.name});
  
  static const List<CurrencyDto> availableCurrencies = [
    CurrencyDto(code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham'),
    CurrencyDto(code: 'AFN', symbol: '؋', name: 'Afghan Afghani'),
    CurrencyDto(code: 'ALL', symbol: 'L', name: 'Albanian Lek'),
    CurrencyDto(code: 'AMD', symbol: '֏', name: 'Armenian Dram'),
    CurrencyDto(code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder'),
    CurrencyDto(code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza'),
    CurrencyDto(code: 'ARS', symbol: '\$', name: 'Argentine Peso'),
    CurrencyDto(code: 'AUD', symbol: 'A\$', name: 'Australian Dollar'),
    CurrencyDto(code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin'),
    CurrencyDto(code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat'),
    CurrencyDto(code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark'),
    CurrencyDto(code: 'BBD', symbol: '\$', name: 'Barbadian Dollar'),
    CurrencyDto(code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka'),
    CurrencyDto(code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev'),
    CurrencyDto(code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar'),
    CurrencyDto(code: 'BIF', symbol: 'FBu', name: 'Burundian Franc'),
    CurrencyDto(code: 'BMD', symbol: '\$', name: 'Bermudan Dollar'),
    CurrencyDto(code: 'BND', symbol: '\$', name: 'Brunei Dollar'),
    CurrencyDto(code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano'),
    CurrencyDto(code: 'BRL', symbol: 'R\$', name: 'Brazilian Real'),
    CurrencyDto(code: 'BSD', symbol: '\$', name: 'Bahamian Dollar'),
    CurrencyDto(code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum'),
    CurrencyDto(code: 'BWP', symbol: 'P', name: 'Botswanan Pula'),
    CurrencyDto(code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble'),
    CurrencyDto(code: 'BZD', symbol: '\$', name: 'Belize Dollar'),
    CurrencyDto(code: 'CAD', symbol: 'CA\$', name: 'Canadian Dollar'),
    CurrencyDto(code: 'CDF', symbol: 'FC', name: 'Congolese Franc'),
    CurrencyDto(code: 'CHF', symbol: 'CHF', name: 'Swiss Franc'),
    CurrencyDto(code: 'CLP', symbol: '\$', name: 'Chilean Peso'),
    CurrencyDto(code: 'CNY', symbol: '¥', name: 'Chinese Yuan'),
    CurrencyDto(code: 'COP', symbol: '\$', name: 'Colombian Peso'),
    CurrencyDto(code: 'CRC', symbol: '₡', name: 'Costa Rican Colón'),
    CurrencyDto(code: 'CUP', symbol: '\$', name: 'Cuban Peso'),
    CurrencyDto(code: 'CVE', symbol: '\$', name: 'Cape Verdean Escudo'),
    CurrencyDto(code: 'CZK', symbol: 'Kč', name: 'Czech Koruna'),
    CurrencyDto(code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc'),
    CurrencyDto(code: 'DKK', symbol: 'kr', name: 'Danish Krone'),
    CurrencyDto(code: 'DOP', symbol: '\$', name: 'Dominican Peso'),
    CurrencyDto(code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar'),
    CurrencyDto(code: 'EGP', symbol: '£', name: 'Egyptian Pound'),
    CurrencyDto(code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa'),
    CurrencyDto(code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr'),
    CurrencyDto(code: 'EUR', symbol: '€', name: 'Euro'),
    CurrencyDto(code: 'FJD', symbol: '\$', name: 'Fijian Dollar'),
    CurrencyDto(code: 'FKP', symbol: '£', name: 'Falkland Islands Pound'),
    CurrencyDto(code: 'FOK', symbol: 'kr', name: 'Faroese Króna'),
    CurrencyDto(code: 'GBP', symbol: '£', name: 'British Pound'),
    CurrencyDto(code: 'GEL', symbol: '₾', name: 'Georgian Lari'),
    CurrencyDto(code: 'GGP', symbol: '£', name: 'Guernsey Pound'),
    CurrencyDto(code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi'),
    CurrencyDto(code: 'GIL', symbol: 'Ǥ', name: 'FF Gil'),
    CurrencyDto(code: 'GIP', symbol: '£', name: 'Gibraltar Pound'),
    CurrencyDto(code: 'GMD', symbol: 'D', name: 'Gambian Dalasi'),
    CurrencyDto(code: 'GNF', symbol: 'FG', name: 'Guinean Franc'),
    CurrencyDto(code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal'),
    CurrencyDto(code: 'GYD', symbol: '\$', name: 'Guyanaese Dollar'),
    CurrencyDto(code: 'HKD', symbol: 'HK\$', name: 'Hong Kong Dollar'),
    CurrencyDto(code: 'HNL', symbol: 'L', name: 'Honduran Lempira'),
    CurrencyDto(code: 'HRK', symbol: '€', name: 'Croatian Kuna (replaced by Euro)'),
    CurrencyDto(code: 'HTG', symbol: 'G', name: 'Haitian Gourde'),
    CurrencyDto(code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint'),
    CurrencyDto(code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah'),
    CurrencyDto(code: 'ILS', symbol: '₪', name: 'Israeli New Shekel'),
    CurrencyDto(code: 'IMP', symbol: '£', name: 'Isle of Man Pound'),
    CurrencyDto(code: 'INR', symbol: '₹', name: 'Indian Rupee'),
    CurrencyDto(code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar'),
    CurrencyDto(code: 'IRR', symbol: '﷼', name: 'Iranian Rial'),
    CurrencyDto(code: 'ISK', symbol: 'kr', name: 'Icelandic Króna'),
    CurrencyDto(code: 'JEP', symbol: '£', name: 'Jersey Pound'),
    CurrencyDto(code: 'JMD', symbol: '\$', name: 'Jamaican Dollar'),
    CurrencyDto(code: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar'),
    CurrencyDto(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
    CurrencyDto(code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling'),
    CurrencyDto(code: 'KGS', symbol: 'сом', name: 'Kyrgystani Som'),
    CurrencyDto(code: 'KHR', symbol: '៛', name: 'Cambodian Riel'),
    CurrencyDto(code: 'KID', symbol: '\$', name: 'Kiribati Dollar'),
    CurrencyDto(code: 'KMF', symbol: 'CF', name: 'Comorian Franc'),
    CurrencyDto(code: 'KRW', symbol: '₩', name: 'South Korean Won'),
    CurrencyDto(code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar'),
    CurrencyDto(code: 'KYD', symbol: '\$', name: 'Cayman Islands Dollar'),
    CurrencyDto(code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge'),
    CurrencyDto(code: 'LAK', symbol: '₭', name: 'Laotian Kip'),
    CurrencyDto(code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound'),
    CurrencyDto(code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee'),
    CurrencyDto(code: 'LRD', symbol: '\$', name: 'Liberian Dollar'),
    CurrencyDto(code: 'LSL', symbol: 'L', name: 'Lesotho Loti'),
    CurrencyDto(code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar'),
    CurrencyDto(code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham'),
    CurrencyDto(code: 'MDL', symbol: 'L', name: 'Moldovan Leu'),
    CurrencyDto(code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary'),
    CurrencyDto(code: 'MKD', symbol: 'ден', name: 'Macedonian Denar'),
    CurrencyDto(code: 'MMK', symbol: 'Ks', name: 'Myanmar Kyat'),
    CurrencyDto(code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik'),
    CurrencyDto(code: 'MOP', symbol: 'P', name: 'Macanese Pataca'),
    CurrencyDto(code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya'),
    CurrencyDto(code: 'MUR', symbol: '₨', name: 'Mauritian Rupee'),
    CurrencyDto(code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa'),
    CurrencyDto(code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha'),
    CurrencyDto(code: 'MXN', symbol: '\$', name: 'Mexican Peso'),
    CurrencyDto(code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit'),
    CurrencyDto(code: 'MZN', symbol: 'MT', name: 'Mozambican Metical'),
    CurrencyDto(code: 'NAD', symbol: '\$', name: 'Namibian Dollar'),
    CurrencyDto(code: 'NGN', symbol: '₦', name: 'Nigerian Naira'),
    CurrencyDto(code: 'NIO', symbol: 'C\$', name: 'Nicaraguan Córdoba'),
    CurrencyDto(code: 'NOK', symbol: 'kr', name: 'Norwegian Krone'),
    CurrencyDto(code: 'NPR', symbol: '₨', name: 'Nepalese Rupee'),
    CurrencyDto(code: 'NZD', symbol: 'NZ\$', name: 'New Zealand Dollar'),
    CurrencyDto(code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial'),
    CurrencyDto(code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa'),
    CurrencyDto(code: 'PEN', symbol: 'S/', name: 'Peruvian Sol'),
    CurrencyDto(code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina'),
    CurrencyDto(code: 'PHP', symbol: '₱', name: 'Philippine Peso'),
    CurrencyDto(code: 'PKR', symbol: '₨', name: 'Pakistani Rupee'),
    CurrencyDto(code: 'PLN', symbol: 'zł', name: 'Polish Zloty'),
    CurrencyDto(code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani'),
    CurrencyDto(code: 'QAR', symbol: 'ر.ق', name: 'Qatari Rial'),
    CurrencyDto(code: 'RON', symbol: 'lei', name: 'Romanian Leu'),
    CurrencyDto(code: 'RSD', symbol: 'дин.', name: 'Serbian Dinar'),
    CurrencyDto(code: 'RUB', symbol: '₽', name: 'Russian Ruble'),
    CurrencyDto(code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc'),
    CurrencyDto(code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal'),
    CurrencyDto(code: 'SBD', symbol: '\$', name: 'Solomon Islands Dollar'),
    CurrencyDto(code: 'SCR', symbol: '₨', name: 'Seychellois Rupee'),
    CurrencyDto(code: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound'),
    CurrencyDto(code: 'SEK', symbol: 'kr', name: 'Swedish Krona'),
    CurrencyDto(code: 'SGD', symbol: '\$', name: 'Singapore Dollar'),
    CurrencyDto(code: 'SHP', symbol: '£', name: 'Saint Helena Pound'),
    CurrencyDto(code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone'),
    CurrencyDto(code: 'SOS', symbol: 'S', name: 'Somali Shilling'),
    CurrencyDto(code: 'SRD', symbol: '\$', name: 'Surinamese Dollar'),
    CurrencyDto(code: 'SSP', symbol: '£', name: 'South Sudanese Pound'),
    CurrencyDto(code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra'),
    CurrencyDto(code: 'SYP', symbol: '£', name: 'Syrian Pound'),
    CurrencyDto(code: 'SZL', symbol: 'L', name: 'Swazi Lilangeni'),
    CurrencyDto(code: 'THB', symbol: '฿', name: 'Thai Baht'),
    CurrencyDto(code: 'TJS', symbol: 'ЅМ', name: 'Tajikistani Somoni'),
    CurrencyDto(code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat'),
    CurrencyDto(code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar'),
    CurrencyDto(code: 'TOP', symbol: 'T\$', name: 'Tongan Paʻanga'),
    CurrencyDto(code: 'TRY', symbol: '₺', name: 'Turkish Lira'),
    CurrencyDto(code: 'TTD', symbol: '\$', name: 'Trinidad and Tobago Dollar'),
    CurrencyDto(code: 'TVD', symbol: '\$', name: 'Tuvaluan Dollar'),
    CurrencyDto(code: 'TWD', symbol: 'NT\$', name: 'New Taiwan Dollar'),
    CurrencyDto(code: 'TZS', symbol: 'Sh', name: 'Tanzanian Shilling'),
    CurrencyDto(code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia'),
    CurrencyDto(code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling'),
    CurrencyDto(code: 'USD', symbol: '\$', name: 'US Dollar'),
    CurrencyDto(code: 'UYU', symbol: '\$', name: 'Uruguayan Peso'),
    CurrencyDto(code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som'),
    CurrencyDto(code: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar'),
    CurrencyDto(code: 'VND', symbol: '₫', name: 'Vietnamese Dong'),
    CurrencyDto(code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu'),
    CurrencyDto(code: 'WST', symbol: 'T', name: 'Samoan Tala'),
    CurrencyDto(code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc'),
    CurrencyDto(code: 'XCD', symbol: '\$', name: 'East Caribbean Dollar'),
    CurrencyDto(code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc'),
    CurrencyDto(code: 'XPF', symbol: '₣', name: 'CFP Franc'),
    CurrencyDto(code: 'YER', symbol: '﷼', name: 'Yemeni Rial'),
    CurrencyDto(code: 'ZAR', symbol: 'R', name: 'South African Rand'),
    CurrencyDto(code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha'),
    CurrencyDto(code: 'ZWL', symbol: '\$', name: 'Zimbabwean Dollar'),
  ];
}